services:
  db:
    image: db
    container_name: db
    environment:
      POSTGRES_DB: sentencebuilderdb
      POSTGRES_PASSWORD: dbuserpwd123
      POSTGRES_USER: dbuser
    build:
      context: ./data
      target: db
    ports:
      - 5432:5432
    restart: always

      #  db:
      #    environment:
      #      ACCEPT_EULA: "Y"
      #      SA_PASSWORD: Admin@123
      #      MSSQL_SA_PASSWORD: Admin@123
      #    image: mcr.microsoft.com/mssql/server:2019-latest
      #    restart: always
      #    ports:
      #      - "1433:1433"
      #    healthcheck:
      #      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "$$SA_PASSWORD" -Q "SELECT 1" || exit 1
      #      interval: 30s
      #      timeout: 30s
      #      retries: 3
  
  #  db:
  #    build: ./data
  #    environment:
  #      ACCEPT_EULA: "Y"
  #      SA_PASSWORD: Admin@123
  #      MSSQL_SA_PASSWORD: Admin@123
  #    ports:
  #      - "1433:1433"
  #    restart: always
  #  
  api:
    image: sentence-builder-api
    build:
      context: .
      dockerfile: WebAPI/Dockerfile
    depends_on:
      - "db"
    ports:
      - "5242:80"
    environment:
      DB_CONNECTION_STRING: host=db;port=5432;database=sentencebuilderdb;username=dbuser;password=dbuserpwd123